[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/kkharji/redis-derive"]
git = "https://github.com/kkharji/redis-derive"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
